# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c58c555b-5d42-4597-ac4a-3e8a201f24ca";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/fd1d3e31-ef2c-4b6d-9dce-16c85bdd5de2";
      fsType = "ext4";
    };

  fileSystems."/home/extra" =
    { device = "/dev/disk/by-uuid/e5a43a07-aec8-43d0-b470-62715b84dfb7";
      fsType = "ext4";
    };

  fileSystems."/home/storage" =
    { device = "/dev/disk/by-uuid/5B3DDB0E6AD65A37";
      fsType = "ntfs";
    };

  swapDevices = [
    { device = "/dev/disk/by-uuid/9c8d4b67-0f3a-45fa-9235-edd29ea3ee01"; }
  ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
